name: "Build and deploy to Github pages"

env:
  PUBLISH_DIR: "src/Frontend/ServerExplorer/bin/Release/net7.0/publish/wwwroot"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'
      - '**/Backend/**'

  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'
      - '**/Backend/**'

jobs:
  build:
    name: "Build, pack and deploy to Github pages"
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      PROJECT: "src/Frontend/ServerExplorer/ServerExplorer.csproj"
      BUILD_ARCH: "Any CPU"
      BUILD_CONFIG: "Release"

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .Net 7"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
          include_prerelease: true

      - name: "Restore project"
        run: dotnet restore ${{ env.PROJECT }}

      - name: Build
        run: dotnet build ${{ env.PROJECT }} --configuration ${{ env.BUILD_CONFIG }} --no-restore

      - name: "Run unit tests"
        run: dotnet test

      - name: "Publish app"
        run: dotnet publish ${{ env.PROJECT }} --configuration ${{ env.BUILD_CONFIG }}

      - name: "Rewrite base href"
        if: success()
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html

      - name: "Replace configuration file"
        run: echo ${{ vars.frontend_appsettings }} >| ${{ env.PUBLISH_DIR }}/appsettings.json

      # Add .nojekyll file to tell github pages not to treat it
      # as a jekyll site. Which allows files and directories with
      # underscore in them.
      - name: "Add .nojekyll file"
        run: touch ${{ env.PUBLISH_DIR }}/.nojekyll

      # Prevent step from running if there is an outage
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v3
        with:
          pages_threshold: major_outage

      - name: "Commit to Github pages branch"
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          #build_dir: ${{ env.PUBLISH_DIR }}
          build_dir: "src/Frontend/ServerExplorer/bin/Release/net7.0/publish/wwwroot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
